### ISSUE TITLE
报错ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'怎么解决

### ISSUE THREAD

**Issue by duzelin1** [tdj11/KBQA_medical#1]
Traceback (most recent call last):
  File "E:\code\kbqa\KBQA_medical\KBQA_medical\run.py", line 8, in <module>
    from modules import gossip_robot,medical_robot,classifier
  File "E:\code\kbqa\KBQA_medical\KBQA_medical\modules.py", line 19, in <module>
    clf_model = CLFModel('./NLU4/sklearn_Classification/model_file/')
  File "E:\code\kbqa\KBQA_medical\KBQA_medical\NLU4\sklearn_Classification\clf_model.py", line 15, in __init__
    self.LR_clf = pickle.load(open(os.path.join(self.model_save_path,'LR.pkl'),'rb'))
ModuleNotFoundError: No module named 'sklearn.linear_model.logistic'

**Comment by tdj11** [comment]
可能是版本的问题，你试一下scikit-learn=0.19.2版本
